name: athlas
description: Athlas Sports App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.0.3
  envied: ^0.3.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: 2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  grpc: ^3.1.0
  intl: 0.17.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  protobuf: ^2.1.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.0.2
  rxdart: ^0.27.6

dev_dependencies:
  build_runner: ^2.3.2
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  retrofit_generator: ^6.0.0+1
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.0.1

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  # assets:
  # Add all product images
